FROM node:18

WORKDIR /app/api

# Install dependencies
COPY package*.json ./
RUN npm install --verbose

# Copy source code
COPY . .


# Expose port
EXPOSE 3000

# Run migrations and start development server
CMD sh -c "npm run typeorm:migrate && npm run dev" 